/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AuthedRouteImport } from './routes/_authed'
import { Route as HealthzRouteImport } from './routes/healthz'
import { Route as AuthedIndexRouteImport } from './routes/_authed/index'
import { Route as AuthedBelegeRouteImport } from './routes/_authed/belege'
import { Route as AuthedExportRouteImport } from './routes/_authed/export'
import { Route as AuthedHaushaltRouteImport } from './routes/_authed/haushalt'
import { Route as ApiSplatRouteImport } from './routes/api/$'
import { Route as LoginIndexRouteImport } from './routes/login/index'
import { Route as LoginSentRouteImport } from './routes/login/sent'
import { Route as LoginVerifyRouteImport } from './routes/login/verify'

const AuthedRoute = AuthedRouteImport.update({
  id: '/_authed',
  getParentRoute: () => rootRouteImport,
} as any)
const HealthzRoute = HealthzRouteImport.update({
  id: '/healthz',
  path: '/healthz',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthedIndexRoute = AuthedIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AuthedRoute,
} as any)
const AuthedBelegeRoute = AuthedBelegeRouteImport.update({
  id: '/belege',
  path: '/belege',
  getParentRoute: () => AuthedRoute,
} as any)
const AuthedExportRoute = AuthedExportRouteImport.update({
  id: '/export',
  path: '/export',
  getParentRoute: () => AuthedRoute,
} as any)
const AuthedHaushaltRoute = AuthedHaushaltRouteImport.update({
  id: '/haushalt',
  path: '/haushalt',
  getParentRoute: () => AuthedRoute,
} as any)
const ApiSplatRoute = ApiSplatRouteImport.update({
  id: '/api/$',
  path: '/api/$',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginIndexRoute = LoginIndexRouteImport.update({
  id: '/login/',
  path: '/login/',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginSentRoute = LoginSentRouteImport.update({
  id: '/login/sent',
  path: '/login/sent',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginVerifyRoute = LoginVerifyRouteImport.update({
  id: '/login/verify',
  path: '/login/verify',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof AuthedIndexRoute
  '/healthz': typeof HealthzRoute
  '/belege': typeof AuthedBelegeRoute
  '/export': typeof AuthedExportRoute
  '/haushalt': typeof AuthedHaushaltRoute
  '/api/$': typeof ApiSplatRoute
  '/login/sent': typeof LoginSentRoute
  '/login/verify': typeof LoginVerifyRoute
  '/login/': typeof LoginIndexRoute
}
export interface FileRoutesByTo {
  '/healthz': typeof HealthzRoute
  '/belege': typeof AuthedBelegeRoute
  '/export': typeof AuthedExportRoute
  '/haushalt': typeof AuthedHaushaltRoute
  '/api/$': typeof ApiSplatRoute
  '/login/sent': typeof LoginSentRoute
  '/login/verify': typeof LoginVerifyRoute
  '/': typeof AuthedIndexRoute
  '/login': typeof LoginIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_authed': typeof AuthedRouteWithChildren
  '/healthz': typeof HealthzRoute
  '/_authed/belege': typeof AuthedBelegeRoute
  '/_authed/export': typeof AuthedExportRoute
  '/_authed/haushalt': typeof AuthedHaushaltRoute
  '/api/$': typeof ApiSplatRoute
  '/login/sent': typeof LoginSentRoute
  '/login/verify': typeof LoginVerifyRoute
  '/_authed/': typeof AuthedIndexRoute
  '/login/': typeof LoginIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/healthz'
    | '/belege'
    | '/export'
    | '/haushalt'
    | '/api/$'
    | '/login/sent'
    | '/login/verify'
    | '/login/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/healthz'
    | '/belege'
    | '/export'
    | '/haushalt'
    | '/api/$'
    | '/login/sent'
    | '/login/verify'
    | '/'
    | '/login'
  id:
    | '__root__'
    | '/_authed'
    | '/healthz'
    | '/_authed/belege'
    | '/_authed/export'
    | '/_authed/haushalt'
    | '/api/$'
    | '/login/sent'
    | '/login/verify'
    | '/_authed/'
    | '/login/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  AuthedRoute: typeof AuthedRouteWithChildren
  HealthzRoute: typeof HealthzRoute
  ApiSplatRoute: typeof ApiSplatRoute
  LoginSentRoute: typeof LoginSentRoute
  LoginVerifyRoute: typeof LoginVerifyRoute
  LoginIndexRoute: typeof LoginIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_authed': {
      id: '/_authed'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/healthz': {
      id: '/healthz'
      path: '/healthz'
      fullPath: '/healthz'
      preLoaderRoute: typeof HealthzRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authed/': {
      id: '/_authed/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof AuthedIndexRouteImport
      parentRoute: typeof AuthedRoute
    }
    '/_authed/belege': {
      id: '/_authed/belege'
      path: '/belege'
      fullPath: '/belege'
      preLoaderRoute: typeof AuthedBelegeRouteImport
      parentRoute: typeof AuthedRoute
    }
    '/_authed/export': {
      id: '/_authed/export'
      path: '/export'
      fullPath: '/export'
      preLoaderRoute: typeof AuthedExportRouteImport
      parentRoute: typeof AuthedRoute
    }
    '/_authed/haushalt': {
      id: '/_authed/haushalt'
      path: '/haushalt'
      fullPath: '/haushalt'
      preLoaderRoute: typeof AuthedHaushaltRouteImport
      parentRoute: typeof AuthedRoute
    }
    '/api/$': {
      id: '/api/$'
      path: '/api/$'
      fullPath: '/api/$'
      preLoaderRoute: typeof ApiSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login/': {
      id: '/login/'
      path: '/login'
      fullPath: '/login/'
      preLoaderRoute: typeof LoginIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login/sent': {
      id: '/login/sent'
      path: '/login/sent'
      fullPath: '/login/sent'
      preLoaderRoute: typeof LoginSentRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login/verify': {
      id: '/login/verify'
      path: '/login/verify'
      fullPath: '/login/verify'
      preLoaderRoute: typeof LoginVerifyRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface AuthedRouteChildren {
  AuthedBelegeRoute: typeof AuthedBelegeRoute
  AuthedExportRoute: typeof AuthedExportRoute
  AuthedHaushaltRoute: typeof AuthedHaushaltRoute
  AuthedIndexRoute: typeof AuthedIndexRoute
}

const AuthedRouteChildren: AuthedRouteChildren = {
  AuthedBelegeRoute: AuthedBelegeRoute,
  AuthedExportRoute: AuthedExportRoute,
  AuthedHaushaltRoute: AuthedHaushaltRoute,
  AuthedIndexRoute: AuthedIndexRoute,
}

const AuthedRouteWithChildren =
  AuthedRoute._addFileChildren(AuthedRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  AuthedRoute: AuthedRouteWithChildren,
  HealthzRoute: HealthzRoute,
  ApiSplatRoute: ApiSplatRoute,
  LoginSentRoute: LoginSentRoute,
  LoginVerifyRoute: LoginVerifyRoute,
  LoginIndexRoute: LoginIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
