/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as BelegeRouteImport } from './routes/belege'
import { Route as ExportRouteImport } from './routes/export'
import { Route as HaushaltRouteImport } from './routes/haushalt'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const BelegeRoute = BelegeRouteImport.update({
  id: '/belege',
  path: '/belege',
  getParentRoute: () => rootRouteImport,
} as any)
const ExportRoute = ExportRouteImport.update({
  id: '/export',
  path: '/export',
  getParentRoute: () => rootRouteImport,
} as any)
const HaushaltRoute = HaushaltRouteImport.update({
  id: '/haushalt',
  path: '/haushalt',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/belege': typeof BelegeRoute
  '/export': typeof ExportRoute
  '/haushalt': typeof HaushaltRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/belege': typeof BelegeRoute
  '/export': typeof ExportRoute
  '/haushalt': typeof HaushaltRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/belege': typeof BelegeRoute
  '/export': typeof ExportRoute
  '/haushalt': typeof HaushaltRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/belege' | '/export' | '/haushalt'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/belege' | '/export' | '/haushalt'
  id: '__root__' | '/' | '/belege' | '/export' | '/haushalt'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  BelegeRoute: typeof BelegeRoute
  ExportRoute: typeof ExportRoute
  HaushaltRoute: typeof HaushaltRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/belege': {
      id: '/belege'
      path: '/belege'
      fullPath: '/belege'
      preLoaderRoute: typeof BelegeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/export': {
      id: '/export'
      path: '/export'
      fullPath: '/export'
      preLoaderRoute: typeof ExportRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/haushalt': {
      id: '/haushalt'
      path: '/haushalt'
      fullPath: '/haushalt'
      preLoaderRoute: typeof HaushaltRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  BelegeRoute: BelegeRoute,
  ExportRoute: ExportRoute,
  HaushaltRoute: HaushaltRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
